name: Backend Orders-Query CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
      - "ECO-51-integracion-CI/CD"
    paths:
      - "Backend/orders-query/**"
  pull_request:
    branches:
      - main
    paths:
      - "Backend/orders-query/**"

jobs:
  ci_quality_checks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Backend/orders-query

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalar Dependencias
        run: npm install
      - name: Ejecutar Pruebas (CI)
        run: npm test
      - name: Generar Build (Compilar)
        run: npm run build

  cd_deployment:
    needs: ci_quality_checks
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    env:
      GCP_KEY_TEMP: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    defaults:
      run:
        working-directory: ./Backend/orders-query

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4

      # LOGIN EN DOCKER HUB
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Autenticación con gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: just-turbine-474803-v7

      # CONSTRUIR Y PUBLICAR IMAGEN EN DOCKER HUB
      - name: Construir y Publicar Imagen Docker en DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/orders-query
          file: ./Backend/orders-query/Dockerfile
          push: true
          # Etiqueta con el usuario de DockerHub
          tags: ${{ secrets.DOCKERHUB_USER }}/orders-query:${{ github.sha }}

      # DESPLEGAR A CLOUD RUN USANDO LA IMAGEN DE DOCKER HUB
      - name: Desplegar a Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: orders-query
          region: us-central1
          image: ${{ secrets.DOCKERHUB_USER }}/orders-query:${{ github.sha }}

          # Variables de Entorno (MONGO_URI y KAFKA_BROKER)
          env_vars: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            KAFKA_BROKER=${{ secrets.KAFKA_BROKER }}
