name: Backend Orders-Command CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
      - "ECO-51-integracion-CI/CD"
    paths:
      - "Backend/orders-command/**"
  pull_request:
    branches:
      - main
    paths:
      - "Backend/orders-command/**"

jobs:
  ci_quality_checks:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./Backend/orders-command

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalar Dependencias
        run: npm install
      - name: Ejecutar Pruebas (CI)
        run: npm test
      - name: Generar Build (Compilar)
        run: npm run build

  cd_deployment:
    needs: ci_quality_checks
    if: |
      github.ref == 'refs/heads/main' || 
      github.ref == 'refs/heads/ECO-51-integracion-CI/CD'
    runs-on: ubuntu-latest
    #environment: production
    env:
      GCP_KEY_TEMP: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    defaults:
      run:
        working-directory: ./Backend/orders-command
    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4

      # 1. LOGIN EN DOCKER HUB
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Autenticación con gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: just-turbine-474803-v7

      # 3. CONSTRUIR Y PUBLICAR IMAGEN EN DOCKER HUB
      - name: Construir y Publicar Imagen Docker en DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/orders-command
          file: ./Backend/orders-command/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/orders-command:${{ github.sha }}

      # 4. DESPLEGAR A CLOUD RUN USANDO LA IMAGEN DE DOCKER HUB
      - name: Desplegar a Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: orders-command
          region: us-central1
          # Se usa la imagen de DockerHub (docker.io se asume)
          image: ${{ secrets.DOCKERHUB_USER }}/orders-command:${{ github.sha }}

          # Variables NO sensibles
          env_vars: |
            DB_HOST=34.135.198.65
            DB_PORT=5432
            DB_USERNAME=postgres
            DB_DATABASE=orders
            KAFKA_BROKER=${{ secrets.KAFKA_BROKER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
