name: Backend Payments-Mock CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
      - "ECO-51-integracion-CI/CD"
    paths:
      - "Backend/payments-mock/**"
  pull_request:
    branches:
      - main
    paths:
      - "Backend/payments-mock/**"

jobs:
  ci_quality_checks:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./Backend/payments-mock

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalar Dependencias
        run: npm install
      - name: Ejecutar Pruebas (CI)
        run: npm test
      - name: Generar Build (Compilar)
        run: npm run build

  cd_deployment:
    needs: ci_quality_checks
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    env:
      GCP_KEY_TEMP: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    defaults:
      run:
        working-directory: ./Backend/payments-mock

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4
      - name: Autenticación con gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: just-turbine-474803-v7

      # Login de Docker para Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Construir y Publicar Imagen Docker
      - name: Construir y Publicar Imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/payments-mock
          file: ./Backend/payments-mock/Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/future-infusion-473023-t8/microservices-repo/payments-mock:${{ github.sha }}

      # Desplegar a Cloud Run
      - name: Desplegar a Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: payments-mock
          region: us-central1
          image: us-central1-docker.pkg.dev/future-infusion-473023-t8/microservices-repo/payments-mock:${{ github.sha }}
          env_vars: |
            KAFKA_BROKER=kafka-broker-connection:latest
